server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
    enabled: true
    registryFetchIntervalSeconds: 10 # how often to fetch the registry from Eureka server
    instanceInfoReplicationIntervalSeconds: 10 # how often to replicate instance changes to be replicated to Eureka server
  instance:
    leaseRenewalIntervalInSeconds: 10 # intervalSeconds between subsequent heartbeats sent to Eureka server
    leaseExpirationDurationInSeconds: 20 # time that Eureka server waits since it received last heartbeat before it can evict this instance


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
spring:
  data:
    mongodb:
      uri: mongodb://mongouser:mongodb18@ds227674.mlab.com:27674/customer
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "refresh"]