server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
    register-with-eureka: false
    fetch-registry: false
    enabled: true
    registryFetchIntervalSeconds: 10 # how often to fetch the registry from Eureka server
    instanceInfoReplicationIntervalSeconds: 10 # how often to replicate instance changes to be replicated to Eureka server
  instance:
    leaseRenewalIntervalInSeconds: 10 # intervalSeconds between subsequent heartbeats sent to Eureka server
    leaseExpirationDurationInSeconds: 20 # time that Eureka server waits since it received last heartbeat before it can evict this instance

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

zuul:
  routes:
    vehicle-part-service:
      path: /vehicle/**
      serviceId: vehicle-part-service
    customer-service:
      path: /customer/**
      serviceId: customer-service
    factory-service:
      path: /factory/**
      serviceId: factory-service
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "refresh"]

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
