server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

zuul:
  routes:
    department:
      path: /vehicle/**
      serviceId: vehicle-part-service
    employee:
      path: /customer/**
      serviceId: customer-service
    organization:
      path: /factory/**
      serviceId: factory-service